import { ok, fail } from "@/lib/api-response";
import { getActiveResumePass, getAvailableMockInterviewPayment } from "@/lib/payments/access";
import { assertCsrf } from "@/lib/security/csrf";
import { assertSafeOrigin } from "@/lib/security/request";
import { getSupabaseAdminClient } from "@/lib/supabase/admin";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { logUserAction } from "@/lib/logging";

export async function GET(request: Request) {
  try {
    const supabase = await getSupabaseServerClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return fail("Authentication required", 401);
    }

    const [profileResponse, resumePass, interviewCredit, logsResponse] = await Promise.all([
      supabase.from("users").select("email,mobile,first_name,last_name").eq("id", user.id).single(),
      getActiveResumePass(user.id),
      getAvailableMockInterviewPayment(user.id),
      getSupabaseAdminClient().from("user_access_logs").select("*").eq("user_id", user.id).order("created_at", { ascending: false }).limit(10),
    ]);

    const currentAction = new URL(request.url).searchParams.get("currentAction") ?? "support";

    return ok({
      context: {
        user: profileResponse.data,
        currentAction,
        activePaymentType: resumePass ? "resume_download" : interviewCredit ? "mock_interview" : null,
        lastErrors: [],
        recentLogs: logsResponse.data ?? [],
      },
    });
  } catch (error) {
    return fail(error, 400);
  }
}

export async function POST(request: Request) {
  try {
    await assertSafeOrigin();
    await assertCsrf();

    const supabase = await getSupabaseServerClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return fail("Authentication required", 401);
    }

    const body = (await request.json()) as {
      category: string;
      userMessage: string;
      autogeneratedContext: Record<string, unknown>;
    };

    const admin = getSupabaseAdminClient();
    const { data, error } = await admin
      .from("support_requests")
      .insert({
        user_id: user.id,
        category: body.category,
        status: "open",
        autogenerated_context: body.autogeneratedContext,
        user_message: body.userMessage,
      })
      .select("*")
      .single();

    if (error) {
      throw error;
    }

    await logUserAction({
      userId: user.id,
      actionType: "support_request",
      metadata: {
        supportRequestId: data.id,
        category: body.category,
      },
    });

    return ok({ request: data });
  } catch (error) {
    return fail(error, 400);
  }
}
